name: MIO-BTN-CI/CD

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install Dependencies
      run: npm install
    - name: Generate Static Site
      run: npm run build
        
    - name: Deploy to Coding.net branch
      working-directory: dist
      run: |
        git init
        git config user.name "GitHub Actions Bot"
        git config user.email "samuimomijiyuki@qq.com"
        git add --all .
        git commit -m "Deploy from GitHub: $GITHUB_SHA"
        git push --force --quiet "https://COXIIIaLVD:${{ secrets.CODING_TOKEN }}@e.coding.net/miobutton/MioButton.github.io.git" master:master
    
